export enum FilterKey {
  SUPPLIER_AND_PRICE = "SUPPLIER_AND_PRICE",
  LOCATION = "LOCATION",
  GUEST_RATING = "GUEST_RATING",
  STAR_RATING = "STAR_RATING",
  DISTANCE = "DISTANCE",
  CURRENCY = "CURRENCY",
  SORT_BY = "SORT_BY"
}
